### PR TITLE
Fix #184 by adding support for monads 

### LINKED ISSUE #184: Support monads
We're surprisingly close to being able to support monads (and, with them, list comprehensions). Singletonizing the basic class definitions works. But there's danger on the horizon.

The problem has all to do with CUSKs. As `Note [CUSKification]` in Promote describes, we have little control over when GHC infers a CUSK. And this causes havoc when we want GHC to infer the kind of higher-kinded type variables. Specifically, the `PFunctor` class has a CUSK, and so the user needs to write `class Functor (f :: * -> *)`. Putting in the kind annotations here isn't so, so terrible.

What's worse is that we run into similar problems elsewhere. I haven't tracked down the precise details, but compiling Base.hs on the `monads` branch led to an error where a defunctionalization symbol has a CUSK, and thus inferring that a kind variable should be higher-kinded fails.

Short of fixing CUSKs in GHC, the solution might be to emit GADT-style declarations of defunctionalization symbols instead of H98-style. This would allow us finer control of whether we have a CUSK. (Recall that, with `TypeInType`, all kind variables must be explicitly quantified in order to have a CUSK. So we just won't do that.) This is tantalizingly close. But I'm not going to get there tonight.

Checklist:

* [x] Add `Functor`, `Applicative`, `Monad`, `Alternative`, `MonadPlus`, and `MonadZip` classes, as well as supporting functions. (https://github.com/goldfirere/singletons/pull/314)
* [x] Add `Identity`, `Const`, `Foldable`, and `Traversable`, as well as supporting functions. (https://github.com/goldfirere/singletons/pull/337)
* [ ] Add support for deriving `Functor`, `Foldable`, and `Traversable`. (#344)

### PR DESCRIPTION
**Pull request by RyanGlScott**
At long last, this adds supports for `Monad` and friends. This means we can properly promote and single:

* `do`-notation
* List comprehensions
* `ParallelListComp` (through the `Data.Singletons.Prelude.Monad.Zip` module)

Nothing needed to be changed from the code generation side to make this work—all that was needed was some minor tweaks to the original source code:

* Some extra kind signatures had to be inserted to avoid CUSK issues (e.g., `class Functor (f :: Type -> Type)`).
* Some definitions which rely on infinite lists, such as `some`, `many`, and `forever`, cannot be promoted.

One thing this patch does _not_ do (since it's already pretty large) is add support for `Foldable` and `Traversable`. As a result, I've left some exports from `Data.Singletons.Prelude.Monad` commented out, since they're supposed to be re-exported from `Traversable`.

### CODE REVIEW

**Comment by RyanGlScott** [comment]
Ping?

File: src/Data/Singletons/Prelude/Monad/Internal.hs [hunk 1]
```diff
@@ -0,0 +1,511 @@
...
+      --
+      -- Some functors support an implementation of 'liftA2' that is more
+      -- efficient than the default one. In particular, if 'fmap' is an
+      -- expensive operation, it is likely better to use 'liftA2' than to
+      -- 'fmap' over the structure and then use '<*>'.
+      liftA2 :: (a -> b -> c) -> f a -> f b -> f c
+      liftA2 f x = (<*>) (fmap f x)
+
+      -- -| Sequence actions, discarding the value of the first argument.
+      (*>) :: (f :: Type -> Type) a -> f b -> f b
```
Comment (goldfirere) [inline src/Data/Singletons/Prelude/Monad/Internal.hs]: We should document why `f` needs a kind signature here.

File: src/Data/Singletons/Prelude/Monad/Zip.hs [hunk 2]
```diff
@@ -0,0 +1,99 @@
...
+{-# LANGUAGE TypeInType #-}
+{-# LANGUAGE TypeOperators #-}
+{-# LANGUAGE UndecidableInstances #-}
+
+-----------------------------------------------------------------------------
+-- |
+-- Module      :  Data.Singletons.Prelude.Monad.Zip
+-- Copyright   :  (C) 2018 Ryan Scott
+-- License     :  BSD-style (see LICENSE)
+-- Maintainer  :  Richard Eisenberg (rae@cs.brynmawr.edu)
```
[the remark this answers is not in the document]
Comment (RyanGlScott) [reply src/Data/Singletons/Prelude/Monad/Zip.hs]: I'll do this separately in https://github.com/goldfirere/singletons/issues/331.

File: src/Data/Singletons/Prelude/Monad/Internal.hs (hunk 1 above)
Comment (RyanGlScott) [reply src/Data/Singletons/Prelude/Monad/Internal.hs]: I've added a lengthy `Note [How to get the right kinds when promoting Functor and friends]` to explain the subtleties involved.

**Comment by mstksg** [comment]
Just realized that this also opens the door for declaring Van Laarhoven Lenses :)
