### PR TITLE
Fix #264; or, Data.Singletons.CustomTypeStar fixes

### LINKED ISSUE #264: Data.Singletons.CustomStar headaches/documentation bugs
Having tried out `Data.Singletons.CustomStar` recently, I found a number of things unsatisfying:

1. It's quite easy to stumble upon the same issues that caused #190 in that TH-generated code from `singletonStar` expects certain names to be in scope. Here is a minimal reproducing example:

   ```haskell
   {-# LANGUAGE EmptyCase #-}
   {-# LANGUAGE ExistentialQuantification #-}
   {-# LANGUAGE FlexibleInstances #-}
   {-# LANGUAGE GADTs #-}
   {-# LANGUAGE InstanceSigs #-}
   {-# LANGUAGE RankNTypes #-}
   {-# LANGUAGE ScopedTypeVariables #-}
   {-# LANGUAGE TemplateHaskell #-}
   {-# LANGUAGE TypeFamilies #-}
   {-# LANGUAGE TypeInType #-}
   {-# LANGUAGE TypeOperators #-}
   {-# LANGUAGE UndecidableInstances #-}
   {-# OPTIONS_GHC -ddump-splices #-}
   module Bug where
   
   import Data.Singletons.CustomStar
   import GHC.TypeNats
   
   $(singletonStar [''Nat, ''Bool, ''Maybe])
   ```
   ```
   /u/rgscott/Documents/Hacking/Haskell/Bug.hs:19:3: error:
       Cannot find type annotation for Compare
      |
   19 | $(singletonStar [''Nat, ''Bool, ''Maybe])
      |   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
   
   /u/rgscott/Documents/Hacking/Haskell/Bug.hs:19:3: error:
       Q monad failure
      |
   19 | $(singletonStar [''Nat, ''Bool, ''Maybe])
      |   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
   ```

   I propose to resolve this in a similar fashion as in #190: reexport `module Data.Singletons.TH` from `Data.Singletons.CustomStar`.
2. The documentation for `Data.Singletons.CustomStar` claims that:

   > For example,
   > 
   > ```haskell
   > $(singletonStar [''Nat, ''Bool, ''Maybe])
   > ```
   > 
   > generates the following:
   > 
   > ```haskell
   > data Rep = Nat | Bool | Maybe Rep deriving (Eq, Show, Read)
   > ```
   > 
   > and its singleton.

   I tried to verify this claim by examining the `-ddump-splices` output, and noticed a couple inconsistencies. For instance:

   * `Rep` derives a `Show` instance, but doesn't promote or single it. (This is probably my fault, as I failed to notice this when implementing #191.)
   * Moreover, `singletonStar` conjures up a `POrd Type` and `SOrd Type` instance, but there's no corresponding derived `Ord` instance for `Rep`. Is there any reason there shouldn't be?

3. The documentation for `Data.Singletons.CustomStar` claims that:

   ```haskell
   $(singletonStar [''Nat, ''Bool, ''Maybe])
   ```

   will generate:

   ```haskell
   data instance Sing (a :: *) where
     SNat :: Sing Nat
     SBool :: Sing Bool
     SMaybe :: SingRep a => Sing a -> Sing (Maybe a)
   ```

   What is `SingRep`? Staring at the `-ddump-splices` output reveals that in reality, this is generated:

   ```haskell
   data instance Sing (z_a3pvl :: Type)
     where
       SNat :: Sing Nat
       SBool :: Sing Bool
       SMaybe :: forall (n_a3pvm :: Type). Sing (n_a3pvm :: Type) -> Sing (Maybe n_a3pvm)
   ```

### PR DESCRIPTION
**Pull request by RyanGlScott**
* Export all of `Data.Singletons.TH` from `Data.Singletons.CustomTypeStar`, since the code that `singletonStar` generates needs it
* Bring some uniformity to the instances that `Rep` derives and the instances that it promotes
* Apply various documentation fixes to `Data.Singletons.CustomTypeStar`

### CODE REVIEW

File: src/Data/Singletons/CustomStar.hs [hunk 1]
```diff
@@ -51,15 +54,15 @@ import Data.Singletons.Prelude.Bool
...
+-- > data Rep = Nat | Bool | Maybe Rep deriving (Eq, Ord, Read, Show)
 --
 -- and its singleton. However, because @Rep@ is promoted to @*@, the singleton
 -- is perhaps slightly unexpected:
 --
 -- > data instance Sing (a :: *) where
 -- >   SNat :: Sing Nat
 -- >   SBool :: Sing Bool
--- >   SMaybe :: SingRep a => Sing a -> Sing (Maybe a)
+-- >   SMaybe :: Sing a -> Sing (Maybe a)
```
Comment (goldfirere) [inline src/Data/Singletons/CustomStar.hs]: I think the old version dates back to version <1.0, when we didn't have the `singInstance` magic.
